### ISSUE TITLE
Login & Get Familiar - Ernesto

### ISSUE THREAD

**Issue by iiweby** [iiweby/smb_data_integration#2]
### Task Overview
- Page: [Login to Google Analytics and Squarespace]
- Description: Get familiar with the platforms by logging in and exploring the available data.

### To Do:
1. [ ] Login to Squarespace.
2. [ ] Login to Google Analytics.
3. [ ] View each tab and get familiar with the layout and data.
4. [ ] Bring at least one idea to the next meeting on how we can use the organization's data to help them in any way.

### Expected Outcome:
- You should be familiar with both platforms and their data structures.
- At least one actionable idea from you to leverage the data for organizational benefit.
